"""Durable MAX inbox and outbound instructions; no network or provider work.

Local processing can be repeated after a crash. An outbound send cannot: its
durable sending lease becomes uncertain when lost. Login codes are generated by
the sender only after authorization and never enter these tables.
"""
from __future__ import annotations

from contextlib import contextmanager
from dataclasses import asdict, dataclass, is_dataclass, replace
from datetime import datetime, timedelta, timezone
import hashlib
import json
import re
import secrets
import sqlite3
from uuid import uuid4

from secretary.domain.bot import (
    BotAction, BotButton, BotError, BotEvent, DeterministicReply, EventClaim,
    IntakeReceipt, SendReceipt, text_value, uuid_value,
)
from secretary.domain.team import CommandReceipt, TaskCommand, TaskSnapshot, canonical, content_hash
from secretary.domain.team_auth import AuthError


INVITATION_REPLY_TEXT = 'Запрос на доступ отправлен владельцу. Дождитесь подтверждения.'
BOT_MIGRATION = (
    '''CREATE TABLE bot_events(id TEXT PRIMARY KEY NOT NULL,bot_id TEXT NOT NULL,kind TEXT NOT NULL,
        dedup_hash TEXT NOT NULL,source_hash TEXT NOT NULL,payload_hash TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)),
        created_at REAL NOT NULL,UNIQUE(bot_id,kind,dedup_hash))''',
    '''CREATE TABLE bot_event_state(id TEXT PRIMARY KEY NOT NULL REFERENCES bot_events(id),
        state TEXT NOT NULL CHECK(state IN('queued','processing','done','quarantined','rejected')),
        worker_id TEXT,fence INTEGER NOT NULL DEFAULT 0 CHECK(fence>=0),lease_until REAL,error_code TEXT)''',
    '''CREATE TABLE bot_buttons(id TEXT PRIMARY KEY NOT NULL,event_id TEXT NOT NULL REFERENCES bot_events(id),
        item_key TEXT NOT NULL,nonce TEXT NOT NULL UNIQUE,payload_hash TEXT NOT NULL,
        payload TEXT NOT NULL CHECK(json_valid(payload)),expires_at REAL NOT NULL,UNIQUE(event_id,item_key))''',
    '''CREATE TABLE bot_button_confirmations(event_id TEXT PRIMARY KEY NOT NULL REFERENCES bot_events(id),
        button_id TEXT NOT NULL REFERENCES bot_buttons(id),
        operation_id TEXT NOT NULL REFERENCES team_commands(operation_id))''',
    '''CREATE TABLE bot_proposals(id TEXT PRIMARY KEY NOT NULL,event_id TEXT NOT NULL REFERENCES bot_events(id),
        purpose TEXT NOT NULL,payload_hash TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)),
        UNIQUE(event_id,purpose))''',
    '''CREATE TABLE bot_contexts(id TEXT PRIMARY KEY NOT NULL,event_id TEXT NOT NULL REFERENCES bot_events(id),
        purpose TEXT NOT NULL,actor_id TEXT NOT NULL,bot_id TEXT NOT NULL,chat_id TEXT,
        payload TEXT NOT NULL CHECK(json_valid(payload)),expires_at REAL NOT NULL,UNIQUE(event_id,purpose))''',
    '''CREATE TABLE bot_context_consumptions(event_id TEXT PRIMARY KEY NOT NULL REFERENCES bot_events(id),
        context_id TEXT UNIQUE REFERENCES bot_contexts(id))''',
    '''CREATE TABLE bot_replies(id TEXT PRIMARY KEY NOT NULL,event_id TEXT NOT NULL UNIQUE REFERENCES bot_events(id),
        payload_hash TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)))''',
    '''CREATE TABLE bot_reply_state(id TEXT PRIMARY KEY NOT NULL REFERENCES bot_replies(id),
        state TEXT NOT NULL CHECK(state IN('pending','sending','sent','uncertain','retryable','rejected')),
        worker_id TEXT,fence INTEGER NOT NULL DEFAULT 0 CHECK(fence>=0),lease_until REAL,
        attempt INTEGER NOT NULL DEFAULT 0 CHECK(attempt BETWEEN 0 AND 3),not_before REAL NOT NULL DEFAULT 0,
        receipt TEXT CHECK(receipt IS NULL OR json_valid(receipt)))''',
    'CREATE INDEX bot_event_queue ON bot_event_state(state)',
    'CREATE INDEX bot_reply_queue ON bot_reply_state(state,not_before)',
    *tuple(f'''CREATE TRIGGER {table}_immutable_{verb.lower()} BEFORE {verb} ON {table}
        BEGIN SELECT RAISE(ABORT,'Immutable bot evidence'); END'''
        for table in ('bot_events', 'bot_buttons', 'bot_button_confirmations', 'bot_proposals', 'bot_contexts', 'bot_context_consumptions', 'bot_replies')
        for verb in ('UPDATE', 'DELETE')),
    *tuple(f'''CREATE TRIGGER {table}_replace_guard BEFORE INSERT ON {table}
        WHEN EXISTS(SELECT 1 FROM {table} WHERE {condition})
        BEGIN SELECT RAISE(ABORT,'Immutable bot evidence'); END'''
        for table, condition in (
            ('bot_events', 'id=NEW.id OR (bot_id=NEW.bot_id AND kind=NEW.kind AND dedup_hash=NEW.dedup_hash)'),
            ('bot_buttons', 'id=NEW.id OR nonce=NEW.nonce OR (event_id=NEW.event_id AND item_key=NEW.item_key)'),
            ('bot_button_confirmations', 'event_id=NEW.event_id'),
            ('bot_proposals', 'id=NEW.id OR (event_id=NEW.event_id AND purpose=NEW.purpose)'),
            ('bot_contexts', 'id=NEW.id OR (event_id=NEW.event_id AND purpose=NEW.purpose)'),
            ('bot_context_consumptions', 'context_id=NEW.context_id OR event_id=NEW.event_id'),
            ('bot_replies', 'id=NEW.id OR event_id=NEW.event_id'))),
    *tuple(f'''CREATE TRIGGER {table}_replace_guard BEFORE INSERT ON {table}
        WHEN EXISTS(SELECT 1 FROM {table} WHERE id=NEW.id)
        BEGIN SELECT RAISE(ABORT,'Bot execution cannot be replaced'); END'''
        for table in ('bot_event_state', 'bot_reply_state')),
    *tuple(f'''CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table}
        BEGIN SELECT RAISE(ABORT,'Bot execution cannot be deleted'); END'''
        for table in ('bot_event_state', 'bot_reply_state')),
    '''CREATE TRIGGER bot_event_state_binding BEFORE UPDATE ON bot_event_state
        WHEN NEW.id IS NOT OLD.id OR NEW.fence<OLD.fence
          OR (OLD.state IN('done','quarantined','rejected') AND NEW.state IS NOT OLD.state)
        BEGIN SELECT RAISE(ABORT,'Bot execution cannot regress'); END''',
    '''CREATE TRIGGER bot_reply_state_binding BEFORE UPDATE ON bot_reply_state
        WHEN NEW.id IS NOT OLD.id OR NEW.fence<OLD.fence OR NEW.attempt<OLD.attempt
          OR (OLD.state IN('sent','uncertain','retryable','rejected') AND NEW.state IS NOT OLD.state)
        BEGIN SELECT RAISE(ABORT,'Bot send cannot regress'); END''',
)


@dataclass(frozen=True)
class BotDelivery:
    id: str
    event: BotEvent
    reply: DeterministicReply
    worker_id: str
    fence: int
    lease_until: datetime
    state: str
    attempt: int


def _plain(value):
    if hasattr(value, 'model_dump'):
        return value.model_dump(mode='json', exclude_unset=True)
    if is_dataclass(value):
        return {key: _plain(item) for key, item in vars(value).items()}
    if isinstance(value, (tuple, list)):
        return [_plain(item) for item in value]
    if isinstance(value, dict):
        return {key: _plain(item) for key, item in value.items()}
    return value


def _encoded(value, maximum=131072):
    try:
        data = canonical(_plain(value))
        if len(data.encode('utf-8')) > maximum:
            raise ValueError
        return data
    except (ValueError, TypeError, UnicodeError):
        raise BotError('bot_payload_invalid') from None


def _event_json(payload):
    value = json.loads(payload)
    value['project_ids'] = tuple(value['project_ids'])
    value['media'] = tuple(value['media'])
    return BotEvent(**value)


def _reply_json(payload):
    value = json.loads(payload)
    value['buttons'] = tuple(tuple(BotButton(**button) for button in row) for row in value['buttons'])
    if value['receipt'] is not None:
        value['receipt'] = CommandReceipt.model_validate(value['receipt'])
    return DeterministicReply(**value)


def _key(value, maximum=128):
    if not isinstance(value, str) or not re.fullmatch(r'[A-Za-z0-9_:-]{1,' + str(maximum) + '}', value):
        raise BotError('bot_key_invalid')
    return value


class BotRepository:
    def __init__(self, db, team, auth, clock=None):
        if db.path != team.db.path or db.path != auth.db.path:
            raise BotError('bot_database_mismatch')
        self.db, self.team, self.auth = db, team, auth
        self.clock = clock or (lambda: datetime.now(timezone.utc))

    def _now(self):
        value = self.clock()
        if not isinstance(value, datetime) or value.tzinfo is None or value.utcoffset() is None:
            raise BotError('bot_clock_invalid')
        return value.astimezone(timezone.utc)

    @contextmanager
    def _transaction(self, *, intake=False):
        # TeamDatabase already enabled WAL. Reissuing journal_mode on webhook
        # intake could wait before busy_timeout was installed.
        conn = sqlite3.connect(self.db.path, timeout=.2 if intake else 15, isolation_level=None)
        conn.row_factory = sqlite3.Row
        try:
            conn.execute('PRAGMA foreign_keys=ON')
            conn.execute('PRAGMA busy_timeout=' + ('200' if intake else '15000'))
            conn.execute('BEGIN IMMEDIATE')
            yield conn
            conn.commit()
        except sqlite3.OperationalError as error:
            conn.rollback()
            if 'locked' in str(error).lower() or 'busy' in str(error).lower():
                raise BotError('bot_storage_busy') from None
            raise BotError('bot_storage_unavailable') from None
        except BaseException:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _load_event(self, conn, identifier):
        row = conn.execute('SELECT * FROM bot_events WHERE id=?', (identifier,)).fetchone()
        if not row:
            raise BotError('bot_event_unavailable')
        try:
            value = _event_json(row['payload'])
            if value.event_id != row['id'] or content_hash(json.loads(row['payload'])) != row['payload_hash']:
                raise ValueError
            return value
        except (ValueError, TypeError, KeyError):
            raise BotError('bot_storage_corrupt') from None

    def _bound(self, conn, event):
        stored = self._load_event(conn, event.event_id)
        if _encoded(stored) != _encoded(event):
            raise BotError('bot_event_changed')
        if stored.quarantine_reason:
            raise BotError('bot_event_quarantined')
        if stored.actor_id is None:
            if not stored.invitation_id or stored.kind != 'invite_bot_started':
                raise BotError('bot_actor_unknown')
            try:
                invitation, _ = self.auth._invitation(conn, invitation_id=stored.invitation_id)
            except AuthError:
                raise BotError('bot_invitation_invalid') from None
            if (invitation['revoked'] or invitation['candidate_user_id'] != stored.user_id
                    or self._now().timestamp() >= invitation['expires_at']):
                raise BotError('bot_invitation_invalid')
            return stored
        try:
            member = self.auth._member(conn, identifier=stored.actor_id)
        except AuthError:
            raise BotError('bot_actor_changed') from None
        if (not member or not member.enabled or member.max_user_id != stored.user_id
                or member.revision != stored.actor_revision or member.project_ids != stored.project_ids):
            raise BotError('bot_actor_changed')
        return stored

    def intake(self, event: BotEvent):
        if not isinstance(event, BotEvent):
            raise BotError('bot_event_invalid')
        # Revalidate even a frozen dataclass; nested attachments are not frozen.
        event = BotEvent(**asdict(event))
        dedup = hashlib.sha256(event.dedup_key.encode('utf-8')).hexdigest()
        source = asdict(event)
        for name in ('event_id', 'actor_id', 'actor_revision', 'project_ids', 'invitation_id'):
            source.pop(name)
        # Provider delivery metadata may differ on retransmission. The first
        # accepted timestamp remains immutable as the future date anchor.
        if event.kind in {'message_created', 'message_callback', 'bot_started', 'invite_bot_started'}:
            source.pop('timestamp_ms')
        source['invitation_value'] = (hashlib.sha256(event.invitation_value.encode('utf-8')).hexdigest()
                                      if event.invitation_value is not None else None)
        # Fingerprint the bounded normalized wire shape before the smaller
        # durable-payload limit decides whether to sanitize into quarantine.
        source_hash = content_hash(json.loads(_encoded(source, 2 * 1024 * 1024)))
        with self._transaction(intake=True) as conn:
            old = conn.execute('SELECT id,source_hash FROM bot_events WHERE bot_id=? AND kind=? AND dedup_hash=?',
                (event.bot_id, event.kind, dedup)).fetchone()
            if old:
                if old['source_hash'] != source_hash:
                    raise BotError('bot_event_conflict')
                return IntakeReceipt(old['id'], 'duplicate')
            if conn.execute('SELECT 1 FROM bot_events WHERE id=?', (event.event_id,)).fetchone():
                raise BotError('bot_event_id_conflict')
            reason = 'bot_event_invalid' if event.quarantine_reason else None
            if event.kind not in {'message_created', 'message_callback', 'bot_started', 'invite_bot_started'}:
                reason = 'bot_unsupported_event'
            normalized = replace(event, actor_id=None, actor_revision=None, project_ids=(), invitation_id=None,
                                 invitation_value=None, quarantine_reason=None)
            if not reason and event.invitation_value is not None and event.kind in {'bot_started', 'invite_bot_started'}:
                try:
                    invite = self.auth.claim_invitation_in_transaction(conn, event.invitation_value, event.user_id)
                    normalized = replace(normalized, kind='invite_bot_started', invitation_id=invite.id,
                                         text=None, callback_payload=None, media=())
                except AuthError:
                    reason = 'bot_invitation_invalid'
            elif not reason:
                try:
                    member = self.auth._member(conn, max_id=event.user_id) if event.user_id else None
                except AuthError:
                    member, reason = None, 'bot_member_invalid'
                if not member or not member.enabled:
                    reason = reason or 'bot_unknown_user'
                else:
                    normalized = replace(normalized, actor_id=member.id, actor_revision=member.revision,
                                         project_ids=member.project_ids)
            if not reason:
                try:
                    if (not isinstance(event.media, tuple) or len(event.media) > 10
                            or any(not isinstance(item, dict) for item in event.media)):
                        raise BotError('bot_payload_invalid')
                    _encoded(normalized, 65536)
                except BotError:
                    reason = 'bot_event_invalid'
            if reason:
                normalized = replace(normalized, dedup_key=dedup, text=None, callback_payload=None,
                    message_id=None, callback_id=None, media=(), actor_id=None, actor_revision=None,
                    project_ids=(), invitation_id=None, invitation_value=None, quarantine_reason=reason)
            payload = _encoded(normalized, 65536)
            conn.execute('INSERT INTO bot_events VALUES(?,?,?,?,?,?,?,?)', (event.event_id, event.bot_id,
                event.kind, dedup, source_hash, content_hash(json.loads(payload)), payload, self._now().timestamp()))
            state = 'quarantined' if reason else 'queued'
            conn.execute('INSERT INTO bot_event_state(id,state,error_code) VALUES(?,?,?)', (event.event_id, state, reason))
            return IntakeReceipt(event.event_id, state, reason)

    def get_event(self, identifier):
        uuid_value(identifier)
        with self.db.connection() as conn:
            return self._load_event(conn, identifier)

    @staticmethod
    def _lease(worker_id, lease_seconds):
        text_value(worker_id, 128)
        if type(lease_seconds) is not int or not 1 <= lease_seconds <= 3600:
            raise BotError('bot_lease_invalid')

    def _recover(self, conn):
        stamp = self._now().timestamp()
        conn.execute("UPDATE bot_event_state SET state='queued',worker_id=NULL,lease_until=NULL WHERE state='processing' AND lease_until<=?", (stamp,))
        conn.execute("UPDATE bot_reply_state SET state='uncertain',worker_id=NULL,lease_until=NULL WHERE state='sending' AND lease_until<=?", (stamp,))

    def recover_expired(self):
        with self._transaction() as conn:
            self._recover(conn)

    def claim_event(self, worker_id, lease_seconds=60):
        self._lease(worker_id, lease_seconds)
        with self._transaction() as conn:
            self._recover(conn)
            row = conn.execute('''SELECT current.* FROM bot_event_state current
                JOIN bot_events event ON event.id=current.id WHERE current.state='queued'
                AND NOT EXISTS(SELECT 1 FROM bot_events prior JOIN bot_event_state state ON state.id=prior.id
                    WHERE prior.rowid<event.rowid AND state.state IN('queued','processing')
                    AND prior.bot_id=event.bot_id
                    AND json_extract(prior.payload,'$.user_id') IS json_extract(event.payload,'$.user_id'))
                ORDER BY event.rowid LIMIT 1''').fetchone()
            if not row:
                return None
            until, fence = self._now() + timedelta(seconds=lease_seconds), row['fence'] + 1
            conn.execute("UPDATE bot_event_state SET state='processing',worker_id=?,fence=?,lease_until=? WHERE id=?",
                         (worker_id, fence, until.timestamp(), row['id']))
            return EventClaim(self._load_event(conn, row['id']), worker_id, fence, until)

    def _event_claim(self, conn, claim, *, done=False):
        if not isinstance(claim, EventClaim):
            raise BotError('bot_claim_invalid')
        row = conn.execute('SELECT * FROM bot_event_state WHERE id=?', (claim.event.event_id,)).fetchone()
        if (not row or row['worker_id'] != claim.worker_id or row['fence'] != claim.fence
                or row['state'] not in ({'processing', 'done'} if done else {'processing'})
                or row['state'] != 'done' and row['lease_until'] <= self._now().timestamp()):
            raise BotError('bot_claim_lost')
        return row

    def authorize_event(self, claim):
        with self._transaction() as conn:
            self._event_claim(conn, claim)
            return self._bound(conn, claim.event)

    def renew_event(self, claim, lease_seconds=60):
        self._lease(claim.worker_id, lease_seconds)
        with self._transaction() as conn:
            self._event_claim(conn, claim)
            self._bound(conn, claim.event)
            until = max(claim.lease_until, self._now() + timedelta(seconds=lease_seconds))
            conn.execute('UPDATE bot_event_state SET lease_until=? WHERE id=?', (until.timestamp(), claim.event.event_id))
            return replace(claim, lease_until=until)

    def fail_event(self, claim, error_code):
        error_code = _key(error_code)
        with self._transaction() as conn:
            self._event_claim(conn, claim)
            conn.execute("UPDATE bot_event_state SET state='rejected',error_code=? WHERE id=?", (error_code, claim.event.event_id))

    def finish_event(self, claim, reply: DeterministicReply):
        if not isinstance(reply, DeterministicReply):
            raise BotError('bot_reply_invalid')
        # CommandPreview is an application result. Its full command lives in the
        # immutable confirm button, not in the outbound message instruction.
        payload = _encoded(DeterministicReply(reply.text, reply.buttons, reply.sensitive_action, reply.receipt))
        reply = _reply_json(payload)
        if (re.search(r'[0-9a-f]{32}\.[A-Z2-7]{10}', payload)
                or reply.sensitive_action and (reply.buttons or reply.receipt)):
            raise BotError('bot_sensitive_reply_forbidden')
        with self._transaction() as conn:
            state = self._event_claim(conn, claim, done=True)
            old = conn.execute('SELECT payload FROM bot_replies WHERE event_id=?', (claim.event.event_id,)).fetchone()
            if old:
                if old['payload'] != payload:
                    raise BotError('bot_reply_conflict')
                return
            if state['state'] == 'done':
                raise BotError('bot_storage_corrupt')
            event = self._bound(conn, claim.event)
            if event.actor_id is None and (reply.text != INVITATION_REPLY_TEXT or reply.buttons or reply.receipt or reply.sensitive_action):
                raise BotError('bot_invitation_reply_only')
            identifier = str(uuid4())
            conn.execute('INSERT INTO bot_replies VALUES(?,?,?,?)', (identifier, event.event_id, content_hash(json.loads(payload)), payload))
            conn.execute("INSERT INTO bot_reply_state(id,state) VALUES(?,'pending')", (identifier,))
            conn.execute("UPDATE bot_event_state SET state='done' WHERE id=?", (event.event_id,))

    def _snapshot(self, conn, event, task_id):
        row = conn.execute('SELECT * FROM team_projections WHERE task_id=?', (task_id,)).fetchone()
        if not row:
            raise BotError('bot_task_unavailable')
        snapshot = TaskSnapshot.model_validate_json(row['payload'])
        if (snapshot.task_id != row['task_id'] or snapshot.project_id != row['project_id']
                or snapshot.revision != row['revision'] or snapshot.project_id not in event.project_ids):
            raise BotError('bot_task_unavailable')
        return snapshot

    def store_button(self, event, *, key, action, task_id=None, command=None, operation_id=None, expires_seconds=900):
        key, action = _key(key), _key(action, 512)
        if type(expires_seconds) is not int or not 1 <= expires_seconds <= 86400:
            raise BotError('bot_button_invalid')
        if command is not None:
            command = TaskCommand.model_validate(command.model_dump(exclude_unset=True))
            if task_id is not None and task_id != command.task_id or operation_id is not None and operation_id != command.operation_id:
                raise BotError('bot_button_invalid')
            task_id, operation_id = command.task_id, command.operation_id
        if operation_id is not None:
            uuid_value(operation_id)
        with self._transaction() as conn:
            event = self._bound(conn, event)
            if event.actor_id is None:
                raise BotError('bot_actor_unknown')
            snapshot = self._snapshot(conn, event, task_id) if task_id else None
            if command and command.project_id not in event.project_ids:
                raise BotError('bot_task_unavailable')
            body = {'action': action, 'task_id': task_id, 'command': _plain(command), 'operation_id': operation_id,
                'actor_id': event.actor_id, 'actor_revision': event.actor_revision, 'project_ids': event.project_ids,
                'bot_id': event.bot_id, 'user_id': event.user_id, 'chat_id': event.chat_id,
                'task_project_id': snapshot.project_id if snapshot else None,
                'task_revision': snapshot.revision if snapshot else None,
                'task_fingerprint': snapshot.remote_fingerprint if snapshot else None, 'expires_seconds': expires_seconds}
            payload = _encoded(body)
            old = conn.execute('SELECT * FROM bot_buttons WHERE event_id=? AND item_key=?', (event.event_id, key)).fetchone()
            if old:
                # Compare input intent, not current projection, to support local
                # processing replay after the task advanced.
                previous = json.loads(old['payload'])
                for name in ('task_revision', 'task_fingerprint'):
                    body[name] = previous[name]
                if _encoded(body) != old['payload']:
                    raise BotError('bot_button_conflict')
                return old['nonce']
            if command and snapshot and (command.expected_revision != snapshot.revision or command.expected_fingerprint != snapshot.remote_fingerprint):
                raise BotError('bot_button_stale')
            nonce = 'b_' + secrets.token_urlsafe(32)
            conn.execute('INSERT INTO bot_buttons VALUES(?,?,?,?,?,?,?)', (str(uuid4()), event.event_id, key, nonce,
                content_hash(json.loads(payload)), payload, (self._now() + timedelta(seconds=expires_seconds)).timestamp()))
            return nonce

    def _button(self, conn, event):
        event = self._bound(conn, event)
        if event.actor_id is None or event.kind != 'message_callback' or not event.callback_payload:
            raise BotError('bot_button_unavailable')
        row = conn.execute('SELECT * FROM bot_buttons WHERE nonce=?', (event.callback_payload,)).fetchone()
        if not row:
            raise BotError('bot_button_expired')
        value = json.loads(row['payload'])
        if content_hash(value) != row['payload_hash']:
            raise BotError('bot_storage_corrupt')
        if (value['actor_id'] != event.actor_id or value['actor_revision'] != event.actor_revision
                or value['user_id'] != event.user_id or value['bot_id'] != event.bot_id
                or tuple(value['project_ids']) != event.project_ids):
            raise BotError('bot_button_forbidden')
        command = TaskCommand.model_validate(value['command']) if value['command'] else None
        accepted = command and conn.execute('SELECT 1 FROM team_commands WHERE operation_id=?', (command.operation_id,)).fetchone()
        confirmed = conn.execute('SELECT * FROM bot_button_confirmations WHERE event_id=?', (event.event_id,)).fetchone()
        if row['expires_at'] <= self._now().timestamp() and not (
                confirmed and value['action'] == 'confirm' and command and accepted
                and confirmed['button_id'] == row['id'] and confirmed['operation_id'] == command.operation_id):
            raise BotError('bot_button_expired')
        if value['task_id'] and not accepted:
            snapshot = self._snapshot(conn, event, value['task_id'])
            if (snapshot.project_id != value['task_project_id'] or snapshot.revision != value['task_revision']
                    or snapshot.remote_fingerprint != value['task_fingerprint']):
                raise BotError('bot_button_stale')
        return BotAction(action=value['action'], task_id=value['task_id'], command=command,
            operation_id=value['operation_id'], expected_revision=value['task_revision'],
            expected_fingerprint=value['task_fingerprint'])

    def resolve_button(self, event):
        with self._transaction() as conn:
            return self._button(conn, event)

    def confirm_button(self, event):
        with self._transaction() as conn:
            action = self._button(conn, event)
            if action.action != 'confirm' or action.command is None:
                raise BotError('bot_confirmation_required')
            receipt = self.team.accept_command_in_transaction(conn, event.actor_id, action.command,
                                                               expected_actor_revision=event.actor_revision)
            button = conn.execute('SELECT id FROM bot_buttons WHERE nonce=?', (event.callback_payload,)).fetchone()
            old = conn.execute('SELECT * FROM bot_button_confirmations WHERE event_id=?', (event.event_id,)).fetchone()
            if old:
                if old['button_id'] != button['id'] or old['operation_id'] != action.command.operation_id:
                    raise BotError('bot_confirmation_conflict')
            else:
                conn.execute('INSERT INTO bot_button_confirmations VALUES(?,?,?)',
                             (event.event_id, button['id'], action.command.operation_id))
            return receipt

    def save_proposal(self, event, text, *, task_id=None, purpose='intent'):
        text_value(text, 4000)
        purpose = _key(purpose)
        with self._transaction() as conn:
            event = self._bound(conn, event)
            if event.actor_id is None:
                raise BotError('bot_actor_unknown')
            if task_id:
                self._snapshot(conn, event, task_id)
            payload = _encoded({'text': text, 'task_id': task_id, 'actor_id': event.actor_id,
                                'actor_revision': event.actor_revision, 'project_ids': event.project_ids})
            old = conn.execute('SELECT * FROM bot_proposals WHERE event_id=? AND purpose=?', (event.event_id, purpose)).fetchone()
            if old:
                if payload != old['payload']:
                    raise BotError('bot_proposal_conflict')
                return old['id']
            identifier = str(uuid4())
            conn.execute('INSERT INTO bot_proposals VALUES(?,?,?,?,?)', (identifier, event.event_id, purpose,
                         content_hash(json.loads(payload)), payload))
            return identifier

    def save_context(self, event, task_id, purpose):
        if purpose not in {'result', 'due'}:
            raise BotError('bot_context_invalid')
        with self._transaction() as conn:
            event = self._bound(conn, event)
            if event.actor_id is None:
                raise BotError('bot_actor_unknown')
            if event.kind == 'message_callback' and event.callback_payload:
                button = self._button(conn, event)
                if button.task_id != task_id or button.action != ('done' if purpose == 'result' else 'due'):
                    raise BotError('bot_context_invalid')
            snapshot = self._snapshot(conn, event, task_id)
            old = conn.execute('SELECT * FROM bot_contexts WHERE event_id=? AND purpose=?', (event.event_id, purpose)).fetchone()
            if old:
                if json.loads(old['payload'])['command']['task_id'] != task_id:
                    raise BotError('bot_context_conflict')
                return
            identifier = str(uuid4())
            command = TaskCommand(operation_id=identifier, project_id=snapshot.project_id, task_id=task_id,
                expected_revision=snapshot.revision, expected_fingerprint=snapshot.remote_fingerprint, action='link', values={})
            payload = _encoded({'actor_revision': event.actor_revision, 'project_ids': event.project_ids, 'command': command})
            conn.execute('INSERT INTO bot_contexts VALUES(?,?,?,?,?,?,?,?)', (identifier, event.event_id, purpose,
                event.actor_id, event.bot_id, event.chat_id, payload, (self._now() + timedelta(seconds=900)).timestamp()))

    def read_context(self, event):
        with self._transaction() as conn:
            event = self._bound(conn, event)
            if not event.actor_id or not event.text or not event.text.strip() or event.media or event.kind != 'message_created':
                return None
            decision = conn.execute('SELECT context_id FROM bot_context_consumptions WHERE event_id=?', (event.event_id,)).fetchone()
            if decision and decision['context_id'] is None:
                return None
            row = conn.execute('SELECT * FROM bot_contexts WHERE id=?', (decision['context_id'],)).fetchone() if decision else conn.execute('''
                SELECT c.*,x.event_id AS consumed_by FROM bot_contexts c
                JOIN bot_events origin ON origin.id=c.event_id JOIN bot_events incoming ON incoming.id=?
                LEFT JOIN bot_context_consumptions x ON x.context_id=c.id
                WHERE c.actor_id=? AND c.bot_id=? AND origin.rowid<incoming.rowid
                  AND json_extract(origin.payload,'$.timestamp_ms')<=?
                ORDER BY c.rowid DESC LIMIT 1''', (event.event_id, event.actor_id, event.bot_id, event.timestamp_ms)).fetchone()
            if not decision and row and (row['consumed_by'] is not None or row['expires_at'] <= self._now().timestamp()):
                row = None
            if not row:
                if not decision:
                    conn.execute('INSERT INTO bot_context_consumptions(event_id,context_id) VALUES(?,NULL)', (event.event_id,))
                return None
            body = json.loads(row['payload'])
            if body['actor_revision'] != event.actor_revision or tuple(body['project_ids']) != event.project_ids:
                if not decision:
                    conn.execute('INSERT INTO bot_context_consumptions(event_id,context_id) VALUES(?,NULL)', (event.event_id,))
                return None
            command = TaskCommand.model_validate(body['command'])
            snapshot = self._snapshot(conn, event, command.task_id)
            if snapshot.revision != command.expected_revision or snapshot.remote_fingerprint != command.expected_fingerprint:
                raise BotError('bot_context_stale')
            if not decision:
                conn.execute('INSERT INTO bot_context_consumptions(event_id,context_id) VALUES(?,?)', (event.event_id, row['id']))
            return BotAction(row['purpose'], command.task_id, command, command.operation_id)

    def _delivery(self, conn, row):
        evidence = conn.execute('SELECT * FROM bot_replies WHERE id=?', (row['id'],)).fetchone()
        if not evidence or content_hash(json.loads(evidence['payload'])) != evidence['payload_hash']:
            raise BotError('bot_storage_corrupt')
        return BotDelivery(row['id'], self._load_event(conn, evidence['event_id']), _reply_json(evidence['payload']),
            row['worker_id'], row['fence'], datetime.fromtimestamp(row['lease_until'], timezone.utc), row['state'], row['attempt'])

    def claim_reply(self, worker_id, lease_seconds=60):
        self._lease(worker_id, lease_seconds)
        with self._transaction() as conn:
            self._recover(conn)
            row = conn.execute("SELECT * FROM bot_reply_state WHERE state='pending' AND not_before<=? ORDER BY rowid LIMIT 1", (self._now().timestamp(),)).fetchone()
            if not row:
                return None
            until = self._now() + timedelta(seconds=lease_seconds)
            conn.execute("UPDATE bot_reply_state SET state='sending',worker_id=?,fence=fence+1,attempt=attempt+1,lease_until=? WHERE id=?",
                         (worker_id, until.timestamp(), row['id']))
            return self._delivery(conn, conn.execute('SELECT * FROM bot_reply_state WHERE id=?', (row['id'],)).fetchone())

    def _reply_claim(self, conn, delivery):
        if not isinstance(delivery, BotDelivery):
            raise BotError('bot_claim_invalid')
        row = conn.execute('SELECT * FROM bot_reply_state WHERE id=?', (delivery.id,)).fetchone()
        if (not row or row['state'] != 'sending' or row['worker_id'] != delivery.worker_id or row['fence'] != delivery.fence
                or row['lease_until'] <= self._now().timestamp()):
            raise BotError('bot_claim_lost')
        actual = self._delivery(conn, row)
        if actual.event != delivery.event or actual.reply != delivery.reply or actual.attempt != delivery.attempt:
            raise BotError('bot_claim_invalid')
        return actual

    def authorize_reply(self, delivery):
        with self._transaction() as conn:
            actual = self._reply_claim(conn, delivery)
            self._bound(conn, actual.event)
            return actual

    def renew_reply(self, delivery, lease_seconds=60):
        self._lease(delivery.worker_id, lease_seconds)
        with self._transaction() as conn:
            actual = self._reply_claim(conn, delivery)
            self._bound(conn, actual.event)
            until = max(actual.lease_until, self._now() + timedelta(seconds=lease_seconds))
            conn.execute('UPDATE bot_reply_state SET lease_until=? WHERE id=?', (until.timestamp(), actual.id))
            return replace(actual, lease_until=until)

    def finish_reply(self, delivery, receipt: SendReceipt):
        if not isinstance(receipt, SendReceipt):
            raise BotError('bot_receipt_invalid')
        receipt = SendReceipt(**asdict(receipt))
        if receipt.operation_id != delivery.id:
            raise BotError('bot_receipt_invalid')
        if receipt.error_code is not None:
            _key(receipt.error_code)
        with self._transaction() as conn:
            actual = self._reply_claim(conn, delivery)
            state, after = receipt.state, self._now().timestamp()
            if state == 'retryable':
                if receipt.error_code != 'max_rate_limited':
                    state = 'uncertain'
                elif not actual.reply.sensitive_action and actual.attempt < 3:
                    state, after = 'pending', after + (receipt.retry_after if receipt.retry_after is not None else 1)
            conn.execute('UPDATE bot_reply_state SET state=?,not_before=?,receipt=? WHERE id=?',
                         (state, after, _encoded(receipt), delivery.id))
