import type { components } from '../generated/api';
import { request } from './api';
import type { AttributionSnapshot, IdentificationState, ParticipantRoster, PersonProfile } from '../types/api';

export type AddParticipant = components['schemas']['AddParticipant'];
export type PatchParticipant = components['schemas']['PatchParticipant'];
export type ReviewAttribution = components['schemas']['ReviewAttribution'];
// OpenAPI exposes one conditional ProcessRequest. Local commands narrow its
// required scope through the identically constrained generated bypass DTO.
export type IdentifyCommand = components['schemas']['BypassIdentification'] & Pick<components['schemas']['ProcessRequest'], 'retry'>;
export type BypassCommand = components['schemas']['BypassIdentification'];
const path = (id: string) => `/meetings/${encodeURIComponent(id)}`;
const write = <T,>(url: string, body: unknown, method = 'POST') => request<T>(url, { method, body: JSON.stringify(body) });
export const speakersApi = {
  profiles: () => request<PersonProfile[]>('/participants'),
  roster: (id: string) => request<ParticipantRoster>(`${path(id)}/participants`),
  add: (id: string, body: AddParticipant) => write<ParticipantRoster>(`${path(id)}/participants`, body),
  patch: (id: string, participantId: string, body: PatchParticipant) => write<ParticipantRoster>(`${path(id)}/participants/${encodeURIComponent(participantId)}`, body, 'PATCH'),
  attribution: (id: string, version: number) => request<AttributionSnapshot>(`${path(id)}/attribution?version=${version}`),
  review: (id: string, body: ReviewAttribution) => write<AttributionSnapshot>(`${path(id)}/attribution`, body, 'PATCH'),
  identify: (id: string, body: IdentifyCommand) => write<{ job_id: string }>(`${path(id)}/process`, { stage: 'identify_speakers', ...body }),
  run: (id: string, runId: string) => request<IdentificationState>(`${path(id)}/identification-runs/${encodeURIComponent(runId)}`),
  bypass: (id: string, body: BypassCommand) => write<IdentificationState>(`${path(id)}/identification-bypass`, body),
};
